language: node_js
services:
  - mongodb
  - redis-server
sudo: false

addons:
  apt:
    sources:
      - mongodb-2.6-precise

    packages:
      - mongodb-org-server

cache:
  directories:
    - node_modules

# git:
#   depth: 5

node_js:
  - "4.3"
  - "0.12"

env:
  - TEST_BROWSER=true
  - TEST_FOLDER="test/addon test/plugin" RECURSIVE=true
  - TEST_FOLDER="test/bin test/config test/common test/issue test/seeds" RECURSIVE=true
  - TEST_FOLDER=test/server RECURSIVE=true

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script: ./test/travis.sh
