language: node_js
services:
  - mongodb
  - redis-server
sudo: false

addons:
  apt:
    sources:
      - mongodb-2.6-precise

    packages:
      - mongodb-org-server

cache:
  directories:
    - node_modules

node_js:
  - "4.3"
  - "0.12"
  - "0.10"

env:
  - BROWSER=true
  - TEST_FOLDER=test
  - TEST_FOLDER=test/addon RECURSIVE=true
  - TEST_FOLDER=test/common RECURSIVE=true
  - TEST_FOLDER="test/bin test/config test/issue test/seeds" RECURSIVE=true
  - TEST_FOLDER=test/plugin RECURSIVE=true
  - TEST_FOLDER=test/server RECURSIVE=true

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script: ./test/travis.sh
