environment:
  matrix:
  - nodejs_version: "0.12"
    platform: x64
  - nodejs_version: "0.12"
    platform: x86
  - nodejs_version: "4.2"
    platform: x64
  - nodejs_version: "4.2"
    platform: x86

install:
  - where npm
  - where node
  - ps: Install-Product node $env:nodejs_version $env:platform
  - for /f "delims=" %%a in ('where npm') do cd %%a\.. && npm install npm@latest
  - for /f "delims=" %%a in ('where npm') do cd %%a\.. && npm install node-pre-gyp@latest
  - npm install
  - ps: choco install 7zip.commandline
  - ps: md $env:temp\mongo\data
  - ps: Push-Location $env:temp\mongo
  - ps: Invoke-WebRequest https://fastdl.mongodb.org/win32/mongodb-win32-x86_64-2008plus-2.6.5.zip -OutFile mongodb.zip
  - ps: cmd /c 7za e mongodb.zip
  - ps: cmd /c $env:temp\mongo\mongod.exe --logpath=$env:temp\mongo\log --dbpath=$env:temp\mongo\data\ --smallfiles --install
  - ps: Start-Sleep -Seconds 5
  - ps: net start mongodb
  - ps: Pop-Location
  - ps: Write-Host
  - ps: Write-Host "monogdb installation complete"

build: off

test_script:
  - node --version
  - npm --version
  - npm run test_travis
