environment:
  matrix:
  - nodejs_version: "0.12"
    platform: x64
  # - nodejs_version: "0.12"
  #   platform: x86
  - nodejs_version: "4.2"
    platform: x64
  # - nodejs_version: "4.2"
  #   platform: x86

services:
  - mongodb

install:
  - where npm
  - where node
  - ps: Install-Product node $env:nodejs_version $env:platform
  - for /f "delims=" %%a in ('where npm') do cd %%a\.. && npm install npm@latest
  - for /f "delims=" %%a in ('where npm') do cd %%a\.. && npm install node-pre-gyp@latest
  - npm install

build: off

test_script:
  - node --version
  - npm --version
  - npm run test_ci
